
package com.example.voicerecognitionactivity._46._1._168._192._8080;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "invertService", targetNamespace = "http://192.168.1.46:8080", wsdlLocation = "http://192.168.1.46:8080/wsoap1/invertService?WSDL")
public class InvertService
    extends Service
{

    private final static URL INVERTSERVICE_WSDL_LOCATION;
    private final static WebServiceException INVERTSERVICE_EXCEPTION;
    private final static QName INVERTSERVICE_QNAME = new QName("http://192.168.1.46:8080", "invertService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.46:8080/wsoap1/invertService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INVERTSERVICE_WSDL_LOCATION = url;
        INVERTSERVICE_EXCEPTION = e;
    }

    public InvertService() {
        super(__getWsdlLocation(), INVERTSERVICE_QNAME);
    }

    public InvertService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INVERTSERVICE_QNAME, features);
    }

    public InvertService(URL wsdlLocation) {
        super(wsdlLocation, INVERTSERVICE_QNAME);
    }

    public InvertService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INVERTSERVICE_QNAME, features);
    }

    public InvertService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InvertService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Inverti
     */
    @WebEndpoint(name = "invertPort")
    public Inverti getInvertPort() {
        return super.getPort(new QName("http://192.168.1.46:8080", "invertPort"), Inverti.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Inverti
     */
    @WebEndpoint(name = "invertPort")
    public Inverti getInvertPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://192.168.1.46:8080", "invertPort"), Inverti.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INVERTSERVICE_EXCEPTION!= null) {
            throw INVERTSERVICE_EXCEPTION;
        }
        return INVERTSERVICE_WSDL_LOCATION;
    }

}
