
package com.example.voicerecognitionactivity._46._1._168._192._8080;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "inverti", targetNamespace = "http://192.168.1.46:8080")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Inverti {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "invertchaine", targetNamespace = "http://192.168.1.46:8080", className = "_46._1._168._192._8080.Invertchaine")
    @ResponseWrapper(localName = "invertchaineResponse", targetNamespace = "http://192.168.1.46:8080", className = "_46._1._168._192._8080.InvertchaineResponse")
    @Action(input = "http://192.168.1.46:8080/inverti/invertchaineRequest", output = "http://192.168.1.46:8080/inverti/invertchaineResponse")
    public String invertchaine(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
